In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,precision_score
import pandas as pd
from PIL import Image

In [2]:
train_root="../Dataset/dataset_AMLS_22-23/celeba"
test_root="../Dataset/dataset_AMLS_22-23_test/celeba_test"

In [3]:
df = pd.read_csv(train_root+"/labels.csv")
df

\timg_name\tgender\tsmiling
0                0\t0.jpg\t-1\t1
1                1\t1.jpg\t-1\t1
2                2\t2.jpg\t1\t-1
3               3\t3.jpg\t-1\t-1
4               4\t4.jpg\t-1\t-1
...                          ...
4995        4995\t4995.jpg\t1\t1
4996        4996\t4996.jpg\t1\t1
4997        4997\t4997.jpg\t1\t1
4998        4998\t4998.jpg\t1\t1
4999        4999\t4999.jpg\t1\t1

[5000 rows x 1 columns]

In [4]:
Y_train=[]
for i in range(5000):
    li=df["\timg_name\tgender\tsmiling"][i].split('\t')
    Y_train.append(int(li[3]))
Y_train

[1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1

In [5]:
Y_train=np.array(Y_train)
Y_train=Y_train.reshape(-1,1)
Y_train.shape

(5000, 1)

In [6]:
X_train=[]
for j in range(5000):
    li2=df["\timg_name\tgender\tsmiling"][j].split('\t')
    path=train_root+"/img/"+li2[1]
    im=Image.open(path).convert("RGB")
    im = im.resize((100, 100))
    ii=np.asarray(im)
    ii=ii.flatten()
    X_train.append(ii)
X_train

[array([253, 231, 194, ..., 121,  52,  26], dtype=uint8),
 array([ 66,  51,  44, ..., 139, 119, 112], dtype=uint8),
 array([255, 255, 255, ...,  94,  94,  96], dtype=uint8),
 array([63, 54, 48, ..., 26, 27, 22], dtype=uint8),
 array([152, 197, 203, ..., 146, 196, 200], dtype=uint8),
 array([255, 255, 255, ...,  52,  42,  31], dtype=uint8),
 array([120,  76,  68, ..., 159, 158, 163], dtype=uint8),
 array([26, 29, 34, ..., 26, 25, 30], dtype=uint8),
 array([ 95,  76,  46, ..., 177, 155, 105], dtype=uint8),
 array([ 3,  4,  8, ..., 17, 18, 23], dtype=uint8),
 array([231, 227, 244, ..., 157, 144, 154], dtype=uint8),
 array([ 2,  2,  2, ..., 54, 52, 53], dtype=uint8),
 array([173, 126, 110, ...,  97, 186, 172], dtype=uint8),
 array([229, 157, 109, ...,  32,  30,  18], dtype=uint8),
 array([177, 178, 183, ..., 210, 217, 225], dtype=uint8),
 array([23, 24, 19, ..., 33, 34, 36], dtype=uint8),
 array([171, 206, 226, ..., 253, 198,  69], dtype=uint8),
 array([199, 215, 231, ...,  60,  48,  34], 

In [7]:
X_train=np.array(X_train)
X_train

array([[253, 231, 194, ..., 121,  52,  26],
       [ 66,  51,  44, ..., 139, 119, 112],
       [255, 255, 255, ...,  94,  94,  96],
       ...,
       [ 77, 123,  27, ...,  87,  54,  33],
       [103,  82,  62, ...,  55,  53,  55],
       [103, 106, 115, ...,  42,  42,  42]], dtype=uint8)

In [8]:
df_t=pd.read_csv(test_root+"/labels.csv")
df_t

\timg_name\tgender\tsmiling
0              0\t0.jpg\t-1\t-1
1               1\t1.jpg\t-1\t1
2                2\t2.jpg\t1\t1
3                3\t3.jpg\t1\t1
4              4\t4.jpg\t-1\t-1
..                          ...
995          995\t995.jpg\t1\t1
996          996\t996.jpg\t1\t1
997          997\t997.jpg\t1\t1
998          998\t998.jpg\t1\t1
999          999\t999.jpg\t1\t1

[1000 rows x 1 columns]

In [11]:
Y_test=[]
for i in range(1000):
    li=df_t["\timg_name\tgender\tsmiling"][i].split('\t')
    Y_test.append(int(li[3]))
Y_test

[-1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1

In [12]:
Y_test=np.array(Y_test)
Y_test=Y_test.reshape(-1,1)
Y_test.shape

(1000, 1)

In [13]:
X_test=[]
for j in range(1000):
    li2=df_t["\timg_name\tgender\tsmiling"][j].split('\t')
    path=test_root+"/img/"+li2[1]
    im=Image.open(path).convert("RGB")
    im = im.resize((100, 100))
    ii=np.asarray(im)
    ii=ii.flatten()
    X_test.append(ii)
X_test

[array([252, 252, 250, ..., 118,  86,  61], dtype=uint8),
 array([164,  81, 105, ...,  26,  23,  18], dtype=uint8),
 array([144, 129, 100, ...,  45,  38,  33], dtype=uint8),
 array([16, 23, 31, ..., 36, 37, 52], dtype=uint8),
 array([222, 225, 234, ..., 190, 189, 205], dtype=uint8),
 array([184, 186, 162, ..., 255, 237, 239], dtype=uint8),
 array([241, 241, 239, ...,  66,  64,  69], dtype=uint8),
 array([78, 58, 57, ..., 43, 41, 45], dtype=uint8),
 array([228, 228, 230, ..., 236, 236, 238], dtype=uint8),
 array([17, 16, 22, ..., 89,  9, 10], dtype=uint8),
 array([252, 253, 255, ..., 183, 182,  99], dtype=uint8),
 array([187, 127, 179, ..., 118, 131, 105], dtype=uint8),
 array([83, 96, 78, ..., 26, 28,  7], dtype=uint8),
 array([105, 115, 140, ..., 162, 166, 178], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([ 43,  10,   5, ..., 174, 163, 161], dtype=uint8),
 array([205, 205, 205, ..., 198, 197, 195], dtype=uint8),
 array([139, 140, 134, ..., 214, 207, 189], dtype=

In [14]:
X_test=np.array(X_test)
X_test

array([[252, 252, 250, ..., 118,  86,  61],
       [164,  81, 105, ...,  26,  23,  18],
       [144, 129, 100, ...,  45,  38,  33],
       ...,
       [  0,   0,   0, ...,  60,  52,  39],
       [236, 235, 233, ...,  30,  27,  20],
       [167, 176, 183, ...,  23,  25,  24]], dtype=uint8)

In [15]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1000)#PCA dimension reduction, change n_component to affect the accuracy
X_train=pca.fit_transform(X_train)
X_test=pca.fit_transform(X_test)

In [16]:
model=SVC()
model.fit(X_train,Y_train)

D:\Anaconda\envs\pytorch\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [17]:
Y_pred = model.predict(X_test)
Y_pred

array([-1,  1, -1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1,
       -1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1,  1,
        1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1,  1,  1,
       -1,  1,  1, -1,  1, -1,  1, -1,  1, -1, -1, -1,  1, -1,  1,  1,  1,
       -1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1,  1, -1,  1,  1, -1,  1,
       -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1, -1, -1,  1,
        1, -1,  1, -1, -1,  1,  1,  1, -1,  1, -1, -1, -1, -1, -1,  1,  1,
       -1, -1,  1, -1, -1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,
        1, -1,  1, -1,  1,  1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
        1,  1,  1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,
       -1,  1,  1, -1, -1,  1,  1,  1, -1,  1, -1,  1, -1, -1, -1,  1, -1,
        1, -1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,
        1,  1,  1, -1, -1

In [18]:
accuracy_score(Y_test,Y_pred)

0.456

In [19]:
confusion_matrix(Y_test,Y_pred)

array([[243, 257],
       [287, 213]], dtype=int64)