In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,precision_score
import pandas as pd
from PIL import Image
import os 

In [2]:
train_root="../Dataset/dataset_AMLS_22-23/cartoon_set"
test_root="../Dataset/dataset_AMLS_22-23_test/cartoon_set_test"

In [3]:
df = pd.read_csv(train_root+"/labels.csv")
df

\teye_color\tface_shape\tfile_name
0                        0\t1\t4\t0.png
1                        1\t2\t4\t1.png
2                        2\t2\t3\t2.png
3                        3\t2\t0\t3.png
4                        4\t0\t2\t4.png
...                                 ...
9995               9995\t3\t2\t9995.png
9996               9996\t0\t3\t9996.png
9997               9997\t1\t2\t9997.png
9998               9998\t0\t2\t9998.png
9999               9999\t2\t2\t9999.png

[10000 rows x 1 columns]

In [4]:
Y_train=[]
for i in range(10000):
    li=df["\teye_color\tface_shape\tfile_name"][i].split('\t')
    Y_train.append(int(li[2]))
Y_train

[4,
 4,
 3,
 0,
 2,
 4,
 0,
 3,
 1,
 3,
 0,
 2,
 0,
 3,
 3,
 3,
 0,
 2,
 4,
 3,
 3,
 0,
 1,
 3,
 2,
 2,
 2,
 3,
 0,
 0,
 2,
 2,
 3,
 4,
 0,
 3,
 4,
 4,
 3,
 4,
 2,
 2,
 2,
 3,
 4,
 3,
 2,
 1,
 1,
 3,
 0,
 4,
 3,
 3,
 4,
 0,
 1,
 2,
 3,
 3,
 4,
 2,
 2,
 1,
 4,
 3,
 4,
 1,
 1,
 2,
 0,
 2,
 0,
 1,
 3,
 2,
 3,
 1,
 1,
 1,
 1,
 0,
 0,
 2,
 4,
 1,
 3,
 0,
 0,
 4,
 1,
 2,
 0,
 4,
 3,
 1,
 3,
 3,
 0,
 4,
 1,
 0,
 3,
 2,
 2,
 3,
 4,
 4,
 0,
 3,
 0,
 1,
 0,
 1,
 1,
 3,
 1,
 4,
 4,
 1,
 2,
 0,
 0,
 2,
 0,
 0,
 2,
 3,
 0,
 2,
 2,
 0,
 3,
 0,
 3,
 3,
 1,
 2,
 4,
 0,
 3,
 1,
 1,
 2,
 0,
 4,
 4,
 0,
 2,
 4,
 1,
 2,
 1,
 2,
 4,
 3,
 1,
 0,
 1,
 4,
 1,
 3,
 0,
 4,
 0,
 4,
 3,
 4,
 3,
 2,
 2,
 4,
 2,
 1,
 3,
 2,
 0,
 0,
 3,
 2,
 0,
 3,
 0,
 3,
 0,
 2,
 1,
 3,
 3,
 1,
 0,
 1,
 0,
 0,
 1,
 3,
 4,
 2,
 4,
 2,
 1,
 2,
 2,
 1,
 4,
 2,
 3,
 2,
 3,
 0,
 4,
 3,
 1,
 4,
 3,
 0,
 4,
 0,
 1,
 1,
 0,
 3,
 2,
 2,
 1,
 4,
 2,
 2,
 2,
 2,
 0,
 1,
 2,
 2,
 1,
 1,
 0,
 0,
 4,
 2,
 4,
 1,
 3,
 3,
 1,
 4,
 4,
 4,
 4,
 3,


In [5]:
Y_train=np.array(Y_train)
Y_train=Y_train.reshape(-1,1)
Y_train.shape

(10000, 1)

In [6]:
X_train=[]
for j in range(10000):
    li2=df["\teye_color\tface_shape\tfile_name"][j].split('\t')
    path=train_root+"/img/"+li2[3]
    im=Image.open(path).convert("RGB")
    im = im.resize((200, 200))
    ii=np.asarray(im)
    ii=ii.flatten()
    X_train.append(ii)
X_train

[array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 2

In [7]:
X_train=np.array(X_train)
X_train

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [8]:
df_t=pd.read_csv(test_root+"/labels.csv")
df_t

\teye_color\tface_shape\tfile_name
0                        0\t2\t1\t0.png
1                        1\t1\t4\t1.png
2                        2\t0\t2\t2.png
3                        3\t0\t2\t3.png
4                        4\t3\t3\t4.png
...                                 ...
2495               2495\t4\t4\t2495.png
2496               2496\t2\t4\t2496.png
2497               2497\t2\t4\t2497.png
2498               2498\t4\t4\t2498.png
2499               2499\t3\t4\t2499.png

[2500 rows x 1 columns]

In [15]:
Y_test=[]
for i in range(2500):
    li=df_t["\teye_color\tface_shape\tfile_name"][i].split('\t')
    Y_test.append(int(li[2]))
Y_test

[1,
 4,
 2,
 2,
 3,
 3,
 1,
 2,
 1,
 2,
 3,
 0,
 4,
 1,
 0,
 4,
 1,
 4,
 0,
 0,
 4,
 4,
 3,
 3,
 0,
 1,
 3,
 1,
 1,
 0,
 4,
 2,
 2,
 1,
 4,
 1,
 4,
 0,
 4,
 0,
 3,
 2,
 3,
 3,
 1,
 4,
 2,
 4,
 2,
 0,
 3,
 3,
 2,
 1,
 0,
 2,
 4,
 1,
 0,
 0,
 2,
 4,
 2,
 3,
 2,
 4,
 2,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 4,
 4,
 3,
 0,
 4,
 1,
 0,
 3,
 0,
 3,
 4,
 4,
 4,
 2,
 4,
 2,
 1,
 3,
 1,
 1,
 2,
 0,
 3,
 1,
 3,
 3,
 2,
 2,
 4,
 2,
 1,
 2,
 0,
 3,
 4,
 0,
 4,
 3,
 3,
 0,
 0,
 0,
 3,
 3,
 0,
 3,
 0,
 3,
 3,
 1,
 3,
 3,
 2,
 0,
 4,
 3,
 3,
 4,
 0,
 0,
 4,
 4,
 4,
 3,
 1,
 0,
 4,
 3,
 4,
 0,
 1,
 1,
 2,
 2,
 1,
 0,
 0,
 1,
 3,
 0,
 1,
 2,
 1,
 1,
 4,
 2,
 0,
 0,
 3,
 0,
 2,
 1,
 3,
 2,
 0,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 3,
 0,
 3,
 4,
 4,
 2,
 4,
 4,
 1,
 0,
 3,
 3,
 0,
 0,
 2,
 1,
 1,
 0,
 3,
 1,
 0,
 2,
 0,
 4,
 4,
 2,
 4,
 0,
 0,
 0,
 4,
 2,
 4,
 4,
 1,
 0,
 0,
 0,
 1,
 4,
 4,
 4,
 4,
 1,
 2,
 0,
 1,
 0,
 1,
 3,
 4,
 4,
 2,
 3,
 1,
 0,
 0,
 0,
 4,
 1,
 3,
 4,
 0,
 1,
 4,
 3,
 0,
 1,
 1,
 1,
 3,
 4,
 0,
 2,


In [16]:
Y_test=np.array(Y_test)
Y_test=Y_test.reshape(-1,1)
Y_test.shape

(2500, 1)

In [27]:
X_test=[]
for j in range(2500):
    li2=df_t["\teye_color\tface_shape\tfile_name"][j].split('\t')
    path=test_root+"/img/"+li2[3]
    im=Image.open(path).convert("RGB")
    im = im.resize((100, 100))
    ii=np.asarray(im)
    ii=ii.flatten()
    X_test.append(ii)
X_test

[array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 2

In [28]:
X_test=np.array(X_test)
X_test

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [29]:
from sklearn.decomposition import PCA
pca = PCA(n_components=500)#PCA dimension reduction, change n_component to affect the accuracy
X_train=pca.fit_transform(X_train)
X_test=pca.fit_transform(X_test)

In [30]:
model=SVC()
model.fit(X_train,Y_train)

D:\Anaconda\envs\pytorch\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [31]:
Y_pred = model.predict(X_test)
Y_pred

array([1, 3, 1, ..., 0, 3, 4])

In [32]:
accuracy_score(Y_test,Y_pred)

0.2112

In [33]:
###RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(class_weight='balanced',random_state=37)   
rfc = rfc.fit(X_train, Y_train)
Y_pred = rfc.predict(X_test)
Y_pred

C:\Users\dell\AppData\Local\Temp\ipykernel_19980\3864061182.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc = rfc.fit(X_train, Y_train)


array([1, 3, 1, ..., 0, 3, 0])

In [34]:
accuracy_score(Y_test,Y_pred)

0.2008